### ISSUE TITLE
未匹配的关键词转换成英文失败

### ISSUE THREAD

**Issue by psumhm** [lanvent/plugin_sdwebui#1]
大大，我不会代码，然后发现翻译失败，我用CHATGPT分析了一下，没有匹配到的管家此被存储在unused_keywords然后变成prompt，这个过程会调用Bridge().fetch_translate()将中文翻译成英文，不过在调用的时候发生了错误。错误日志：
[INFO][2023-05-11 08:08:18][sdwebui.py:97] - [SD] translate prompt from zh to en
[INFO][2023-05-11 08:08:18][sdwebui.py:101] - [SD] translate failed: unsupported operand type(s) for +: 'NoneType' and 'str'
[INFO][2023-05-11 08:08:18][sdwebui.py:102] - [SD] translated prompt=猫
chatgpt：这个错误可能是由于Bridge().fetch_translate()方法返回了None，然后代码试图将这个None值和一个字符串进行连接，导致了这个错误。这个方法通过调用self.get_bot("translate")获取一个翻译的机器人，然后调用这个机器人的translate方法进行翻译。要解决这个问题，你需要查看get_bot("translate")返回的机器人的translate方法的实现，看看为什么它会返回None，并确保它在所有情况下都返回一个Reply对象。
请问，这个机器人bot在哪里，然后如何解决这个问题。

**Comment by lanvent** [comment]
没有设置百度翻译api吧，根目录config.json里加

**Comment by psumhm** [comment]
可以啦！
