### ISSUE TITLE
请问大佬怎么更改使用的模型。

### ISSUE THREAD

**Issue by sakura-lj** [lanvent/plugin_sdwebui#12]
因为这个模型太🐍🐍，所以我想要换一个模型。
我通过更改config中的文件中的
"options": {
      "sd_model_checkpoint": "perfectWorld_v2Baked"
}

把perfectWorld_v2Baked模型改为
![image](https://github.com/lanvent/plugin_sdwebui/assets/116950653/952881ae-de2f-4f8b-8186-6a6af4e1ed08)
上面的模型，但是经过测试，模型还是没变。请问模型应该怎么更改啊

**Comment by lanvent** [comment]
1. 确认关键字的结果触发正确，如果是默认配置则不需要输入关键字
2. 修改配置文件后需要重新加载插件或者重启bot程序

**Comment by sakura-lj** [comment]
大佬还是不行，配置文件修改为
![image](https://github.com/lanvent/plugin_sdwebui/assets/116950653/4420cf0f-4f7f-45b3-a569-5752080563ff)
键值与(http://127.0.0.1:7860/sdapi/v1/options )所返回的键一致。
但是模型还是没有更改。以下为日志
![image](https://github.com/lanvent/plugin_sdwebui/assets/116950653/cd07e6e0-2681-4e05-8d80-55c3db9d204b)

**Comment by sakura-lj** [comment]
> 1. 确认关键字的结果触发正确，如果是默认配置则不需要输入关键字
> 2. 修改配置文件后需要重新加载插件或者重启bot程序

大佬还是不行，配置文件修改为
![image](https://github.com/lanvent/plugin_sdwebui/assets/116950653/4420cf0f-4f7f-45b3-a569-5752080563ff)
键值与(http://127.0.0.1:7860/sdapi/v1/options )所返回的键一致。
但是模型还是没有更改。以下为日志
![image](https://github.com/lanvent/plugin_sdwebui/assets/116950653/cd07e6e0-2681-4e05-8d80-55c3db9d204b)

**Comment by lanvent** [comment]
只需要填写.ckpt后缀前的内容

**Comment by sakura-lj** [comment]
> 要填写.ckpt后缀前的

谢谢大佬回复，还是不行欸大佬，模型没有改变，我改为了：
![image](https://github.com/lanvent/plugin_sdwebui/assets/116950653/1e444293-6501-4c78-a943-75a230c8c749)
但是模型还是原来的模型
如下
![mmexport1699548647794](https://github.com/lanvent/plugin_sdwebui/assets/116950653/f7e7e8e2-6b74-48e5-bcad-bd709117bd7b)

**Comment by sakura-lj** [comment]
大佬这是日志
[INFO][2023-11-10 00:47:59][sdwebui.py:34] - [SD] inited
[INFO][2023-11-10 00:48:00][wechat_channel.py:194] - [WX] sendMsg=Reply(type=INFO, content=[INFO]
插件配置已重载), receiver=@29a45f7770752bec23c09cdaaf429dba76db9f45976c51620c14e4bd4ebc064e
[INFO][2023-11-10 00:48:23][sdwebui.py:52] - [SD] image_query=:red heart,
[INFO][2023-11-10 00:48:23][sdwebui.py:105] - [SD] cover options={'sd_model_checkpoint': 'Ekmix-gen3.ckpt'}
[INFO][2023-11-10 00:48:23][sdwebui.py:107] - [SD] params={'sampler_name': 'DPM++ 2M Karras', 'steps': 20, 'width': 512, 'height': 512, 'cfg_scale': 7, 'prompt': 'masterpiece, best quality, red heart,', 'negative_prompt': '(low quality, worst quality:1.4),(bad_prompt:0.8), (monochrome:1.1), (greyscale)', 'enable_hr': False, 'hr_scale': 2, 'hr_upscaler': 'Latent', 'hr_second_pass_steps': 15, 'denoising_strength': 0.7}
[INFO][2023-11-10 00:48:26][wechat_channel.py:215] - [WX] sendImage, receiver=@29a45f7770752bec23c09cdaaf429dba76db9f45976c51620c14e4bd4ebc064e

**Comment by lanvent** [comment]
.ckpt也不用写

**Comment by sakura-lj** [comment]
> .ckpt也不用写

还是不行大佬，配置文件改为了
![image](https://github.com/lanvent/plugin_sdwebui/assets/116950653/982820ce-e6a4-49fc-adf0-c55fa6c90b83)
但是输出还是那个类型的图片
以下为日志：
[INFO][2023-11-10 00:57:47][wechat_channel.py:194] - [WX] sendMsg=Reply(type=INFO, content=[INFO]
插件配置已重载), receiver=@29a45f7770752bec23c09cdaaf429dba76db9f45976c51620c14e4bd4ebc064e
[INFO][2023-11-10 00:57:51][sdwebui.py:52] - [SD] image_query=:red heart,
[INFO][2023-11-10 00:57:51][sdwebui.py:105] - [SD] cover options={'sd_model_checkpoint': 'Ekmix-gen3'}
[INFO][2023-11-10 00:57:51][sdwebui.py:107] - [SD] params={'sampler_name': 'DPM++ 2M Karras', 'steps': 20, 'width': 512, 'height': 512, 'cfg_scale': 7, 'prompt': 'masterpiece, best quality, red heart,', 'negative_prompt': '(low quality, worst quality:1.4),(bad_prompt:0.8), (monochrome:1.1), (greyscale)', 'enable_hr': False, 'hr_scale': 2, 'hr_upscaler': 'Latent', 'hr_second_pass_steps': 15, 'denoising_strength': 0.7}
[INFO][2023-11-10 00:57:54][wechat_channel.py:215] - [WX] sendImage, receiver=@29a45f7770752bec23c09cdaaf429dba76db9f45976c51620c14e4bd4ebc064
